services:
  frontend:
    build: 
      context: ./frontend/cpe-event-app
      dockerfile: Dockerfile
      additional_contexts:
        shared: ./shared
    ports:
      - "3000:3000"
    depends_on:
      - backend

  backend:
    build: 
      context: ./backend
      dockerfile: Dockerfile
      additional_contexts:
        shared: ./shared
    ports:
      - "5000:5000"
    depends_on:
      - "db"
    env_file: ./backend/.env

  db:
    image: postgres:latest
    ports:
      - "5118:5432"
    env_file: ./db/.env
    volumes:
      - ./db:/docker-entrypoint-initdb.d
      
    