services:
  frontend:
    build: ./frontend/cpe-event-app
    ports:
      - "3000:3000"
    depends_on:
      - backend

  backend:
    build: ./backend
    ports:
      - "5000:5000"
    depends_on:
      - "db"

  db:
    image: postgres:latest
    ports:
      - "5432:5432"
    env_file: ./db/.env
    